import type { learningPaths, pathSteps } from "../schema/learning-paths";

export const learningPathData: (typeof learningPaths.$inferInsert)[] = [
  {
    slug: "buddhism-101",
    title: "佛学入门",
    description: "从零开始了解佛教的核心教义和基本概念。适合对佛教感兴趣但没有系统学习经验的初学者。",
    level: "beginner",
    levelLabel: "入门",
    icon: "🌱",
    stepCount: 6,
  },
  {
    slug: "buddhist-doctrine",
    title: "核心教义",
    description: "深入理解四圣谛、十二因缘、三法印等佛教核心教理的哲学内涵，建立扎实的佛学理论基础。",
    level: "intermediate",
    levelLabel: "进阶",
    icon: "📖",
    stepCount: 6,
  },
  {
    slug: "mahayana-philosophy",
    title: "大乘哲学",
    description: "探索中观、唯识、如来藏三大思想体系，理解大乘佛教最精深的哲学思辨。",
    level: "intermediate",
    levelLabel: "进阶",
    icon: "🔍",
    stepCount: 6,
  },
  {
    slug: "buddhist-practice",
    title: "修行方法",
    description: "从止观禅修到六度万行，系统了解佛教的实践法门。涵盖禅修、念佛、持戒等核心修行方法。",
    level: "intermediate",
    levelLabel: "进阶",
    icon: "🧘",
    stepCount: 6,
  },
  {
    slug: "buddhist-history-schools",
    title: "宗派与历史",
    description: "纵览中国佛教八大宗派的历史渊源、核心教义与传承脉络，理解佛教中国化的宏大历程。",
    level: "advanced",
    levelLabel: "深入",
    icon: "🏛️",
    stepCount: 8,
  },
];

export const pathStepData: (typeof pathSteps.$inferInsert)[] = [
  // ===== 佛学入门 =====
  {
    pathId: "REPLACE_buddhism-101", // will be replaced by actual UUID at seed time
    stepNumber: 1,
    title: "什么是佛教",
    description: "佛教是世界三大宗教之一，由释迦牟尼佛于公元前6世纪在古印度创立。佛教既是宗教，也是一套完整的哲学体系和修行方法。",
    guidance: "阅读建议：先看《佛学百科》中「释迦牟尼」词条，了解佛陀生平。",
    relatedSutraSlugs: ["turning-the-dharma-wheel", "forty-two-chapters"],
  },
  {
    pathId: "REPLACE_buddhism-101",
    stepNumber: 2,
    title: "四圣谛——苦",
    description: "苦谛是佛教的出发点——人生有生、老、病、死、爱别离、怨憎会、求不得、五蕴炽盛八种苦。认识到苦并非消极，而是走向解脱的第一步。",
    guidance: "重点理解：佛教说的'苦'不是悲观的抱怨，而是对人生真相的如实观察。",
    relatedTermSlugs: ["duhkha", "four-noble-truths", "five-skandhas"],
  },
  {
    pathId: "REPLACE_buddhism-101",
    stepNumber: 3,
    title: "四圣谛——集与灭",
    description: "集谛指出苦的原因是渴爱（对感官享乐、存在、不存在的渴求）和无明（对诸法实相的不了知）。灭谛宣说苦的彻底止息——涅槃，烦恼的完全断除。",
    guidance: "对比学习：看看「十二因缘」词条，理解烦恼如何一环扣一环地产生苦。",
    relatedTermSlugs: ["four-noble-truths", "nirvana", "klesha", "three-poisons"],
  },
  {
    pathId: "REPLACE_buddhism-101",
    stepNumber: 4,
    title: "四圣谛——道（八正道）",
    description: "道谛即通往灭苦的八正道——正见、正思维、正语、正业、正命、正精进、正念、正定。八正道可分为戒（语、业、命）、定（精进、念、定）、慧（见、思维）三学。",
    guidance: "不要只是背诵八个条目，试着在日常生活中觉察：你现在的言行，符合哪一条？偏离了哪一条？",
    relatedTermSlugs: ["noble-eightfold-path", "three-trainings"],
    relatedSutraSlugs: ["noble-eightfold-path-sutra"],
  },
  {
    pathId: "REPLACE_buddhism-101",
    stepNumber: 5,
    title: "因缘与因果",
    description: "缘起法是佛教最核心的教义——'此有故彼有，此生故彼生；此无故彼无，此灭故彼灭。'一切事物都是因缘和合而生的，没有独立自存的实体。因果论即基于缘起法展开——善因得善果，恶因得恶果。",
    guidance: "阅读「缘起」和「因果」两个词条，理解'缘起'与'因果'的区别与联系。",
    relatedTermSlugs: ["pratityasamutpada", "hetu-phala", "twelve-links", "karma"],
  },
  {
    pathId: "REPLACE_buddhism-101",
    stepNumber: 6,
    title: "三法印与佛教世界观",
    description: "三法印是验证佛法真伪的标准——诸行无常（一切变化不住）、诸法无我（没有独立实体）、涅槃寂静（彻底离苦的安宁）。'诸行无常'是对宇宙万象变化的洞察；'诸法无我'是对万物本质的揭示；'涅槃寂静'是修行的终极目标。",
    guidance: "恭喜完成入门！接下来建议学习「核心教义」路径，深入每一个概念。",
    relatedTermSlugs: ["three-dharma-seals", "anitya", "anatman", "nirvana"],
  },

  // ===== 核心教义 =====
  {
    pathId: "REPLACE_buddhist-doctrine",
    stepNumber: 1,
    title: "缘起的深义",
    description: "深入探讨缘起法的哲学内涵：'缘起'不是简单的因果链，而是万物存在的根本方式——没有任何事物是'自己存在'的，一切都是'关系中的存在'。龙树菩萨用'八不中道'（不生不灭、不常不断、不一不异、不来不去）来表述缘起的究竟义。",
    guidance: "阅读《中论》的相关章节，理解龙树如何论证'缘起即空性'。",
    relatedTermSlugs: ["pratityasamutpada", "shunyata", "middle-way"],
    relatedSutraSlugs: ["mula-madhyamaka-karika"],
  },
  {
    pathId: "REPLACE_buddhist-doctrine",
    stepNumber: 2,
    title: "空性的正确理解",
    description: "空性（Śūnyatā）是大乘佛教最核心的概念，也是最容易被误解的。空'不是'什么都没有'的虚无主义，而是'没有固定不变的自性'——万物虽然是存在的，但没有独立、不变、主宰的实体。《心经》说'色即是空，空即是色'正是此义。",
    guidance: "反复诵读《心经》260字全文，体会'色不异空，空不异色'的深意。",
    relatedTermSlugs: ["shunyata", "tathata", "advaya"],
    relatedSutraSlugs: ["heart-sutra", "diamond-sutra"],
  },
  {
    pathId: "REPLACE_buddhist-doctrine",
    stepNumber: 3,
    title: "五蕴与无我",
    description: "五蕴（色、受、想、行、识）是佛教对众生身心现象的五种分类。'无我'（Anātman）指在这五种聚合中找不到一个常恒独立的主宰者。'无我'不是否定个体的存在，而是破除'有一个永恒不变的我在轮回'的执着。",
    guidance: "禅修练习：静坐十分钟，观察自己的身心——你在哪里能找到那个'我'？",
    relatedTermSlugs: ["five-skandhas", "anatman", "atma-graha"],
  },
  {
    pathId: "REPLACE_buddhist-doctrine",
    stepNumber: 4,
    title: "业力与轮回",
    description: "业（Karma）是身口意行为所产生的潜在能量。业力不是宿命——当下的选择可以改变过去业力的走向。轮回（Saṃsāra）是众生依业力在六道中的流转。理解业力与轮回，才能对自己的生命真正地负起责任。",
    guidance: "思考：如果一切都是缘起无我的，那么'谁'在造业？'谁'在轮回？这是佛学中最深刻的问题之一。",
    relatedTermSlugs: ["karma", "samsara", "six-realms", "three-realms"],
  },
  {
    pathId: "REPLACE_buddhist-doctrine",
    stepNumber: 5,
    title: "戒定慧三学",
    description: "三学是佛教修行的总纲——戒（道德行为规范）是修行的基础，定（心的专注与平静）是修行的核心工具，慧（照见诸法实相的智慧）是修行的最终目标。三者次第相生、相辅相成。",
    guidance: "从五戒开始：不杀生、不偷盗、不邪淫、不妄语、不饮酒。试着在日常生活中实践一个月。",
    relatedTermSlugs: ["three-trainings", "five-precepts", "dhyana", "prajna"],
  },
  {
    pathId: "REPLACE_buddhist-doctrine",
    stepNumber: 6,
    title: "解脱与涅槃",
    description: "解脱（Vimokṣa）是脱离烦恼与业力的束缚。涅槃（Nirvāṇa）是烦恼的彻底止息——不是断灭，而是超越一切二元对立的寂静安乐。大乘佛教更提出'无住涅槃'——不住生死也不住涅槃，为了利益众生而不断示现。",
    guidance: "进阶建议：接下来学习「大乘哲学」，探索龙树、无著等大师的哲学体系。",
    relatedTermSlugs: ["nirvana", "vimoksha", "nirupadhishesha-nirvana"],
    relatedSutraSlugs: ["mahaparinirvana-sutra"],
  },

  // ===== 大乘哲学 =====
  {
    pathId: "REPLACE_mahayana-philosophy",
    stepNumber: 1,
    title: "大乘佛教的兴起",
    description: "大乘佛教（Mahāyāna）约在公元前1世纪兴起，以'自利利他、普度众生'为旗帜，以成佛为最终目标。核心变化：从个人解脱（阿罗汉）转向普遍的成佛之道（菩萨道），发展出空性、佛性、唯识等全新的哲学体系。",
    guidance: "对比阅读：了解声闻乘（阿罗汉道）与菩萨道的区别，理解'回小向大'的意义。",
    relatedTermSlugs: ["mahayana", "bodhisattva", "arhat", "shravaka"],
    relatedSutraSlugs: ["lotus-sutra", "vimalakirti-sutra"],
  },
  {
    pathId: "REPLACE_mahayana-philosophy",
    stepNumber: 2,
    title: "中观学派——龙树的空性哲学",
    description: "中观学派（Mādhyamaka）由龙树菩萨创立，核心方法是'归谬论证'——通过揭示一切概念的内在矛盾来瓦解执着。'八不中道'（不生不灭、不常不断、不一不异、不来不去）是对缘起性空的最精要表述。'空'不是一种'东西'，而是对一切'自性见'的否定。",
    guidance: "阅读龙树《中论》开篇皈敬偈，体会'八不'的哲学力量。",
    relatedTermSlugs: ["middle-way", "shunyata", "two-truths", "anutpattika-dharma-kshanti"],
    relatedSutraSlugs: ["mula-madhyamaka-karika", "sata-sastra"],
  },
  {
    pathId: "REPLACE_mahayana-philosophy",
    stepNumber: 3,
    title: "唯识学派——万法唯识",
    description: "唯识学派（Yogācāra）由无著和世亲兄弟创立，主张'万法唯识'——一切现象都是心识的变现。建立八识体系（前五识、意识、末那识、阿赖耶识）详细分析心理结构。'三性三无性'（遍计所执性、依他起性、圆成实性）是对存在论的精密分析。",
    guidance: "重点理解阿赖耶识——它既是生死轮回的承载者，也是转识成智的可能处。",
    relatedTermSlugs: ["vijnapti-matra", "alaya-vijnana", "jneyavarana", "kleshavarana"],
    relatedSutraSlugs: ["samdhinirmocana-sutra", "vijnaptimatratasiddhi", "trimsika-karika"],
  },
  {
    pathId: "REPLACE_mahayana-philosophy",
    stepNumber: 4,
    title: "如来藏思想——一切众生皆有佛性",
    description: "如来藏（Tathāgatagarbha）意为'如来之胎藏'——一切众生身中隐藏着如来的智慧德相。虽然被烦恼外衣所包裹，但内在的佛性从未减损。《涅槃经》提出'一切众生悉有佛性'，极大地鼓舞了修行者的信心。",
    guidance: "思考：如果一切众生本具佛性，为什么还需要修行？这个问题触及了如来藏思想的核心张力。",
    relatedTermSlugs: ["tathagatagarbha", "buddha-nature", "tathata", "dharmadhatu"],
    relatedSutraSlugs: ["mahaparinirvana-sutra", "srimaladevi-sutra", "awakening-of-faith"],
  },
  {
    pathId: "REPLACE_mahayana-philosophy",
    stepNumber: 5,
    title: "二谛与中道——真理的层次",
    description: "二谛论是佛教哲学的方法论基础：世俗谛（世间共许的日常真理）与胜义谛（圣者证悟的究竟真理）。'中道'不是在两个极端之间取中间，而是超越一切二元对立——离于有与无、常与断。'二谛'的区分不是目的而是方便——最终必须超越二谛的分别才能证入不二。",
    guidance: "阅读月称的《入中论》或宗喀巴的《菩提道次第广论》毗钵舍那章。",
    relatedTermSlugs: ["two-truths", "middle-way", "advaya", "anutpattika-dharma-kshanti"],
  },
  {
    pathId: "REPLACE_mahayana-philosophy",
    stepNumber: 6,
    title: "汉传佛教的判教体系",
    description: "判教是对佛陀一代教法进行分类和判释的理论体系。天台宗的'五时八教'（华严时、阿含时、方等时、般若时、法华涅槃时）是最系统的判教；华严宗有'五教十宗'的判释。判教不仅是学术分类，更是修行路径的指引——告诉修行者在不同阶段应该学习什么。",
    guidance: "对比天台和华严的判教体系，理解两者各自的侧重点。",
    relatedTermSlugs: ["upaya", "dharma-gate"],
    relatedSutraSlugs: ["lotus-sutra", "avatamsaka-sutra"],
  },

  // ===== 修行方法 =====
  {
    pathId: "REPLACE_buddhist-practice",
    stepNumber: 1,
    title: "止观——禅修的两大支柱",
    description: "止（Śamatha）是令心专注一境、止息散乱的修习；观（Vipaśyanā）是以智慧观察诸法实相的修习。'止'如清水，澄净无波；'观'如明镜，照见万物。天台宗以止观为修行核心，智者大师著《摩诃止观》系统阐述。",
    guidance: "实践入门：从'数息'开始——专注呼吸，从一数到十，循环往复。每天十分钟。",
    relatedTermSlugs: ["shamatha-vipashyana", "dhyana", "samadhi", "four-mindfulness"],
  },
  {
    pathId: "REPLACE_buddhist-practice",
    stepNumber: 2,
    title: "四念处——如实观照",
    description: "四念处是原始佛教最基本也最深奥的禅修方法：身念处（观呼吸、观身体动作）、受念处（观察苦乐感受的生灭）、心念处（观察心的贪嗔状态）、法念处（观察五盖、七觉支等法的生灭）。四念处是正念修行的源头。",
    guidance: "推荐阅读一行禅师《正念的奇迹》，了解如何在日常生活中修四念处。",
    relatedTermSlugs: ["four-mindfulness", "seven-factors", "five-hindrances"],
  },
  {
    pathId: "REPLACE_buddhist-practice",
    stepNumber: 3,
    title: "六度——菩萨的六种修行",
    description: "六波罗蜜（六度）是大乘菩萨道的核心修行纲领——布施、持戒、忍辱、精进、禅定、般若。六度以般若为导、前五为伴：布施对治悭贪、持戒对治毁犯、忍辱对治嗔恚、精进治懈怠、禅定治散乱、般若治愚痴。",
    guidance: "实践：每周选择一个'度'作为修行主题。例如本周修'布施'——每天至少做一件不求回报的善行。",
    relatedTermSlugs: ["paramita", "dana", "sila", "kshanti", "virya", "dhyana", "prajna"],
    relatedSutraSlugs: ["six-paramitas-sutra"],
  },
  {
    pathId: "REPLACE_buddhist-practice",
    stepNumber: 4,
    title: "净土法门——念佛往生",
    description: "净土宗以称念'南无阿弥陀佛'名号为主要修行，以往生西方极乐世界为目标。'信、愿、行'三资粮——深信弥陀本愿、切愿往生净土、持名念佛修行。净土法门在汉传佛教中流传最广，因其'三根普被、利钝全收'。",
    guidance: "试着每天早晚各念十声'南无阿弥陀佛'，体会内心的安定感。",
    relatedTermSlugs: ["buddha-recollection", "pure-land-school", "amitabha"],
    relatedSutraSlugs: ["amitabha-sutra", "larger-sukhavati-sutra", "contemplation-sutra"],
  },
  {
    pathId: "REPLACE_buddhist-practice",
    stepNumber: 5,
    title: "禅宗——直指人心",
    description: "禅宗主张'不立文字，教外别传，直指人心，见性成佛'。六祖惠能开创的南宗禅以'顿悟'为特色——'菩提本无树，明镜亦非台，本来无一物，何处惹尘埃'。禅宗不是不要修行，而是打破对'修行形式'的执着，直契心源。",
    guidance: "阅读《六祖坛经》全文，体会惠能直指人心的教法。禅宗不在于文字研究，而在于'参'——反复咀嚼一个话头，直到思维断处。",
    relatedTermSlugs: ["chan-school", "samadhi", "buddha-nature"],
    relatedSutraSlugs: ["platform-sutra", "xin-xin-ming", "gateless-gate"],
  },
  {
    pathId: "REPLACE_buddhist-practice",
    stepNumber: 6,
    title: "日常生活即道场",
    description: "佛法修行不只是打坐和诵经——日常生活中的每一刻都是修行的机会。'一行三昧'是指在一切行住坐卧中保持正念。马祖道一说'平常心是道'——吃饭时吃饭、睡觉时睡觉，不妄想、不分别、不打妄想。修行不是追求某种特殊体验，而是在平凡中找到觉悟。",
    guidance: "今天挑选一件日常小事（洗碗、走路、喝茶），全神贯注地做。看看会有什么不同的体验。",
    relatedTermSlugs: ["upaya", "kalyanamitra"],
  },

  // ===== 宗派与历史 =====
  {
    pathId: "REPLACE_buddhist-history-schools",
    stepNumber: 1,
    title: "佛教的口传时代与部派分裂",
    description: "佛陀涅槃后最初的几个世纪，佛法是依靠僧团的口耳相传保存的。约在佛灭后百年，上座部与大众部因戒律争议而分裂——上座部偏重持戒严谨，大众部偏重适应时代。此后二百年间，更分化为十八部（或二十部），称为'部派佛教'时期。",
    guidance: "访问/f/timeline，从上到下看一遍前500年的佛教历史事件。",
  },
  {
    pathId: "REPLACE_buddhist-history-schools",
    stepNumber: 2,
    title: "大乘佛教的兴起与中观唯识",
    description: "公元前后，大乘佛教运动在印度兴起，以般若经类文献的出现为标志。公元2-3世纪，龙树菩萨建立中观学派；公元4-5世纪，无著与世亲兄弟建立唯识学派。这两个学派构成了大乘佛教哲学的双璧，影响至今。",
    guidance: "回顾「大乘哲学」路径的第一至三步，深入理解中观与唯识。",
    relatedTermSlugs: ["mahayana", "middle-way", "vijnapti-matra"],
    relatedSutraSlugs: ["mula-madhyamaka-karika", "vijnaptimatratasiddhi"],
  },
  {
    pathId: "REPLACE_buddhist-history-schools",
    stepNumber: 3,
    title: "佛教传入中国与格义时期",
    description: "东汉明帝永平十年（公元67年），佛教正式传入中国。初期僧人借用道家和玄学的概念来解释佛教教义，称为'格义佛教'。这个时期虽然理解尚不完全准确，但为佛教在中国的扎根奠定了基础。",
    guidance: "阅读佛学百科中「佛教传入中国」词条，了解这段历史。",
    relatedSutraSlugs: ["forty-two-chapters"],
  },
  {
    pathId: "REPLACE_buddhist-history-schools",
    stepNumber: 4,
    title: "鸠摩罗什与译经黄金时代",
    description: "姚秦弘始三年（401年），鸠摩罗什被迎请至长安，在逍遥园设立国立译经场。罗什翻译的《金刚经》《法华经》《维摩诘经》《中论》等35部294卷，以'意译'为主、文质兼备，奠定了汉传佛教的经典基础。此后真谛、玄奘、不空等译经大师继起，翻译事业持续数百年。",
    guidance: "比较鸠摩罗什和玄奘的翻译风格：一个是'意译'求流畅，一个是'直译'求精确。",
    relatedTermSlugs: ["kumarajiva", "xuanzang"],
    relatedSutraSlugs: ["diamond-sutra", "lotus-sutra", "vimalakirti-sutra"],
  },
  {
    pathId: "REPLACE_buddhist-history-schools",
    stepNumber: 5,
    title: "天台宗与华严宗——中国佛教的两大哲学高峰",
    description: "天台宗由智顗大师（538-597）创立，以《法华经》为宗经，提出'五时八教'判教和'一念三千'的圆融哲学。华严宗由法藏大师（643-712）创立，以《华严经》为宗经，建立'四法界'、'十玄门'、'六相圆融'的宏大哲学体系。两宗代表了中国佛教义理最高水平。",
    guidance: "天台'一念三千'vs 华严'事事无碍'——两者都讲圆融，但入手处不同。",
    relatedTermSlugs: ["tientai", "huayan", "dharmadhatu"],
    relatedSutraSlugs: ["lotus-sutra", "avatamsaka-sutra"],
  },
  {
    pathId: "REPLACE_buddhist-history-schools",
    stepNumber: 6,
    title: "禅宗的创立与分化",
    description: "禅宗自达摩传入中国，至六祖惠能而大盛。惠能后禅宗分化为五家七宗——沩仰、临济、曹洞、云门、法眼（五家），临济宗又分黄龙、杨岐两派（合为七宗）。宋代以降，临济宗和曹洞宗成为流传最广的两支。南宋时，临济宗由荣西传入日本、曹洞宗由道元传入日本。",
    guidance: "阅读禅宗公案——赵州'吃茶去'、临济'喝'、德山'棒'，体会各家的宗风差异。",
    relatedTermSlugs: ["chan-school", "linji-school", "caodong-school"],
    relatedSutraSlugs: ["record-of-linji", "gateless-gate", "blue-cliff-record"],
  },
  {
    pathId: "REPLACE_buddhist-history-schools",
    stepNumber: 7,
    title: "净土宗——最广大的民众信仰",
    description: "净土宗由善导大师（613-681）集大成，以称念'南无阿弥陀佛'为修行核心。净土宗的'易行道'——不需要高深的哲学思辨或复杂的禅修技巧——使得佛法走进了千家万户。'家家阿弥陀，户户观世音'是净土信仰在汉地广泛传播的真实写照。",
    guidance: "净土与禅的融合——永明延寿提倡'禅净双修'，对后世影响深远。",
    relatedTermSlugs: ["pure-land-school", "buddha-recollection"],
    relatedSutraSlugs: ["amitabha-sutra", "larger-sukhavati-sutra", "contemplation-sutra"],
  },
  {
    pathId: "REPLACE_buddhist-history-schools",
    stepNumber: 8,
    title: "佛教的现代转型",
    description: "19世纪末以来，佛教在全球范围内经历了深刻的现代转型。杨文会创立金陵刻经处（1866）开启了中国佛教的近代复兴；太虚大师倡导'人生佛教'推动教理、教制、教产三大改革；一行禅师在西方弘传'入世佛教'；佛光山、法鼓山、慈济等当代佛教团体将佛法与现代生活紧密结合。CBETA（1998）的建立则彻底改变了佛教学术研究的面貌。",
    guidance: "思考：佛教在AI时代应该如何发展和传播？慈悲空间就是这个探索的一部分。",
  },
];
