import type { timelineEvents } from "../schema/timeline-events";

type TimelineInsert = typeof timelineEvents.$inferInsert;

export const timelineData: (typeof timelineEvents.$inferInsert)[] = [
  // ===== 佛陀时代 =====
  {
    slug: "buddha-birth",
    year: -563,
    yearDisplay: "约 公元前 563 年",
    title: "释迦牟尼诞生",
    description: "悉达多·乔达摩出生于古印度迦毗罗卫国（今尼泊尔蓝毗尼），为净饭王与摩耶夫人之子，被预言将成为转轮圣王或觉悟者。",
    category: "人物",
    location: "蓝毗尼（今尼泊尔）",
  },
  {
    slug: "buddha-enlightenment",
    year: -528,
    yearDisplay: "约 公元前 528 年",
    title: "释迦牟尼成道",
    description: "悉达多太子在菩提伽耶的菩提树下，降伏魔军，证得无上正等正觉，成为佛陀（觉悟者），时年三十五岁。",
    category: "人物",
    location: "菩提伽耶（今印度比哈尔邦）",
  },
  {
    slug: "first-turning-dharma-wheel",
    year: -528,
    yearDisplay: "约 公元前 528 年",
    title: "初转法轮",
    description: "佛陀在鹿野苑为憍陈如等五比丘初次说法，宣说四圣谛与八正道，佛教僧团正式成立，佛法僧三宝具足。",
    category: "历史事件",
    location: "鹿野苑（今印度瓦拉纳西附近）",
  },
  {
    slug: "buddha-parinirvana",
    year: -483,
    yearDisplay: "约 公元前 483 年",
    title: "佛陀入般涅槃",
    description: "佛陀在拘尸那罗的娑罗双树间入无余涅槃，世寿八十。临终遗教'以戒为师'，留下'诸行无常，精进勿放逸'的最后教诫。",
    category: "人物",
    location: "拘尸那罗（今印度北方邦）",
  },
  {
    slug: "first-council",
    year: -483,
    yearDisplay: "约 公元前 483 年",
    title: "第一次结集",
    description: "大迦叶尊者召集五百阿罗汉在王舍城七叶窟结集经律，由阿难诵出经藏、优波离诵出律藏，确立佛教经典传承体系。",
    category: "历史事件",
    location: "王舍城（今印度比哈尔邦）",
  },
  {
    slug: "second-council",
    year: -383,
    yearDisplay: "约 公元前 383 年",
    title: "第二次结集",
    description: "因戒律十事争议，耶舍长老召集七百比丘在毗舍离结集，判定十事非法。上座部长老与大众部分裂，为佛教根本分裂之始。",
    category: "历史事件",
    location: "毗舍离（今印度比哈尔邦）",
  },

  // ===== 阿育王时代 =====
  {
    slug: "ashoka-conversion",
    year: -261,
    yearDisplay: "约 公元前 261 年",
    title: "阿育王皈依佛教",
    description: "孔雀王朝阿育王在羯陵伽战争后痛悔杀戮，皈依佛教，从此以佛法治国，推行'正法'政策，佛教由地方宗教走向国际。",
    category: "人物",
    location: "华氏城（今印度巴特那）",
  },
  {
    slug: "third-council",
    year: -250,
    yearDisplay: "约 公元前 250 年",
    title: "第三次结集",
    description: "阿育王支持目犍连子帝须在华氏城召集一千阿罗汉举行第三次结集，编纂《论事》驳斥外道邪见，上座部教义系统化。",
    category: "历史事件",
    location: "华氏城（今印度巴特那）",
  },
  {
    slug: "mahinda-sri-lanka",
    year: -250,
    yearDisplay: "约 公元前 250 年",
    title: "摩哂陀传法至斯里兰卡",
    description: "阿育王之子摩哂陀长老率使团至斯里兰卡弘法，国王天爱帝须皈依佛教，建立大寺，南传上座部佛教确立。",
    category: "历史事件",
    location: "斯里兰卡阿努拉德普勒",
  },

  // ===== 大乘兴起 =====
  {
    slug: "prajnaparamita-emergence",
    year: -100,
    yearDisplay: "约 公元前 100 年",
    title: "般若经类开始编撰",
    description: "大乘佛教最早的经典《般若经》（八千颂）开始编撰，'空性'思想成为大乘佛教的理论基石，标志着大乘运动的兴起。",
    category: "经典译出",
    location: "南印度",
  },
  {
    slug: "fourth-council-kashmir",
    year: 100,
    yearDisplay: "约 公元 100 年",
    title: "迦湿弥罗第四次结集",
    description: "迦腻色迦王支持下，胁尊者召集五百比丘在迦湿弥罗举行第四次结集，编撰《大毗婆沙论》二百卷，说一切有部教义大成。",
    category: "历史事件",
    location: "迦湿弥罗（今克什米尔）",
  },
  {
    slug: "nagarjuna",
    year: 200,
    yearDisplay: "约 公元 150–250 年",
    title: "龙树菩萨开创中观学派",
    description: "龙树（Nāgārjuna）著《中论》《十二门论》《大智度论》等，系统阐述'缘起性空'的中观哲学，被尊为'八宗共祖'，大乘佛教理论体系确立。",
    category: "人物",
    location: "南印度",
  },
  {
    slug: "asanga-vasubandhu",
    year: 350,
    yearDisplay: "约 公元 4–5 世纪",
    title: "无著与世亲开创唯识学派",
    description: "无著（Asaṅga）著《摄大乘论》，世亲（Vasubandhu）著《唯识三十颂》《俱舍论》，瑜伽行派（唯识学派）理论体系完整建立。",
    category: "人物",
    location: "北印度犍陀罗",
  },

  // ===== 佛教传入中国 =====
  {
    slug: "buddhism-enters-china",
    year: 67,
    yearDisplay: "公元 67 年",
    title: "佛教正式传入中国",
    description: "东汉明帝永平十年，迦叶摩腾与竺法兰以白马驮经至洛阳，次年敕建白马寺，翻译《四十二章经》，为中国佛教之始。",
    category: "历史事件",
    location: "洛阳",
  },
  {
    slug: "an-shigao",
    year: 148,
    yearDisplay: "约 公元 148 年",
    title: "安世高来华译经",
    description: "安息国太子安世高抵达洛阳，开始系统翻译小乘禅观经典，是最早来华的著名译经家，开启了中国佛经翻译的第一个时代。",
    category: "经典译出",
    location: "洛阳",
  },
  {
    slug: "lokaksema",
    year: 167,
    yearDisplay: "约 公元 167 年",
    title: "支娄迦谶译出大乘经典",
    description: "月氏人支娄迦谶来洛阳，翻译《道行般若经》《般舟三昧经》等大乘经典，最早将般若思想和弥陀净土信仰引入中国。",
    category: "经典译出",
    location: "洛阳",
  },
  {
    slug: "kumarajiva",
    year: 401,
    yearDisplay: "公元 401 年",
    title: "鸠摩罗什来长安译经",
    description: "后秦姚兴迎请鸠摩罗什至长安，设立中国历史上第一个国立译经场，罗什率八百弟子翻译《金刚经》《法华经》《维摩诘经》《中论》等35部294卷，确立了汉传佛教经典基础。",
    category: "经典译出",
    location: "长安",
  },
  {
    slug: "huiyuan-white-lotus",
    year: 402,
    yearDisplay: "公元 402 年",
    title: "慧远结白莲社",
    description: "慧远大师与僧俗一百二十三人在庐山东林寺结白莲社，共修念佛三昧，开创了中国净土信仰的先河，慧远被尊为净土宗初祖。",
    category: "宗派创立",
    location: "庐山",
  },
  {
    slug: "faxian-journey",
    year: 399,
    yearDisplay: "公元 399–414 年",
    title: "法显西行求法",
    description: "法显以六十余岁高龄自长安出发经西域至印度求取律藏，游历三十余国，从海路归国，著有《佛国记》。为中国第一位成功西行取经的僧人。",
    category: "人物",
    location: "长安→印度→斯里兰卡",
  },

  // ===== 南北朝 =====
  {
    slug: "bodhidharma-arrives",
    year: 520,
    yearDisplay: "约 公元 520 年",
    title: "达摩来华开创禅宗",
    description: "菩提达摩从印度航海至广州，与梁武帝问答不契，一苇渡江至少林寺面壁九年，传法于慧可，开创了汉传禅宗的传承。",
    category: "宗派创立",
    location: "广州→建康→嵩山少林寺",
  },
  {
    slug: "zhiyi-tiantai",
    year: 575,
    yearDisplay: "约 公元 575 年",
    title: "智顗创立天台宗",
    description: "智顗大师（智者大师）在天台山讲经说法，以《法华经》为宗经，建立'五时八教'判教体系，开创了中国最早的佛教宗派天台宗。",
    category: "宗派创立",
    location: "天台山",
  },
  {
    slug: "jizang-sanlun",
    year: 600,
    yearDisplay: "约 公元 600 年",
    title: "吉藏集大成三论宗",
    description: "吉藏大师在长安弘扬《中论》《百论》《十二门论》，建立'二谛'与'八不中道'学说，三论宗正式确立。",
    category: "宗派创立",
    location: "长安",
  },

  // ===== 唐代 =====
  {
    slug: "xuanzang-journey",
    year: 629,
    yearDisplay: "公元 629–645 年",
    title: "玄奘西行取经",
    description: "玄奘法师孤身从长安出发经西域至印度，在那烂陀寺师从戒贤学习唯识教法，遍历印度诸国辩法，携657部梵本回国，历时十七年行程五万里。",
    category: "人物",
    location: "长安→印度→长安",
  },
  {
    slug: "xuanzang-translation",
    year: 645,
    yearDisplay: "公元 645–664 年",
    title: "玄奘主持译经",
    description: "玄奘在长安大慈恩寺主持译场，翻译《大般若经》《瑜伽师地论》《成唯识论》等75部1335卷，开创了中国译经史的新译时代。",
    category: "经典译出",
    location: "长安大慈恩寺",
  },
  {
    slug: "faxiang-school",
    year: 660,
    yearDisplay: "约 公元 660 年",
    title: "玄奘与窥基创立唯识宗",
    description: "玄奘与弟子窥基在长安大慈恩寺创立唯识宗（法相宗），系统阐述八识、三性、转识成智等精密唯识哲学体系。",
    category: "宗派创立",
    location: "长安大慈恩寺",
  },
  {
    slug: "shandao-pure-land",
    year: 650,
    yearDisplay: "约 公元 650 年",
    title: "善导大师集大成净土宗",
    description: "善导大师在长安弘扬净土法门，著《观经四帖疏》确立'他力本愿'教义体系，净土宗成为最具群众基础的中国佛教宗派。",
    category: "宗派创立",
    location: "长安",
  },
  {
    slug: "daoxuan-vinaya",
    year: 650,
    yearDisplay: "约 公元 650 年",
    title: "道宣创立律宗",
    description: "道宣律师隐居终南山，著'南山三大部'系统阐述戒律体系，创立南山律宗，至今为中国汉传佛教戒律的根本依据。",
    category: "宗派创立",
    location: "终南山",
  },
  {
    slug: "fazang-huayan",
    year: 700,
    yearDisplay: "约 公元 700 年",
    title: "法藏创立华严宗",
    description: "法藏大师（贤首大师）著《华严五教章》《华严经探玄记》，建立'五教十宗'判教体系与'十玄门'理论，华严宗正式确立。",
    category: "宗派创立",
    location: "长安",
  },
  {
    slug: "huineng",
    year: 676,
    yearDisplay: "公元 676 年",
    title: "六祖惠能开创南宗禅",
    description: "惠能在广州法性寺以'不是风动不是幡动仁者心动'一语惊人，后住持曹溪宝林寺弘法，开创南宗禅顿悟法门，《六祖坛经》记录其言行。",
    category: "人物",
    location: "广州→曹溪（今广东韶关）",
  },
  {
    slug: "vajrayana-enters-china",
    year: 716,
    yearDisplay: "公元 716 年",
    title: "善无畏与金刚智传入密宗",
    description: "'开元三大士'先后入唐——善无畏（716）译《大日经》、金刚智（720）译《金刚顶经》、不空广译密典，唐密由此确立。",
    category: "宗派创立",
    location: "长安",
  },
  {
    slug: "jianzhen-japan",
    year: 754,
    yearDisplay: "公元 754 年",
    title: "鉴真东渡日本",
    description: "鉴真大师历经六次渡海、双目失明，终在754年抵达日本，传授戒律，建立日本律宗，并传播了中国建筑、雕塑、医药等文化。",
    category: "人物",
    location: "扬州→日本奈良",
  },
  {
    slug: "huichang-persecution",
    year: 845,
    yearDisplay: "公元 845 年",
    title: "会昌法难",
    description: "唐武宗在道士怂恿下发动的灭佛运动，拆毁寺院4600余所、还俗僧尼26万余人。除禅宗外，各宗典籍大量丢失，唐密在中国本土几近灭绝。",
    category: "历史事件",
    location: "全国",
  },

  // ===== 宋代 =====
  {
    slug: "song-printing",
    year: 972,
    yearDisplay: "公元 972 年",
    title: "大藏经首次雕版印刷",
    description: "宋太祖敕令在益州（成都）雕版印刷《大藏经》（开宝藏），是中国历史上第一次大规模印刷佛教大藏经，共5048卷。",
    category: "历史事件",
    location: "成都",
  },
  {
    slug: "linji-school-rise",
    year: 1050,
    yearDisplay: "约 公元 11 世纪",
    title: "临济宗与曹洞宗盛行",
    description: "宋代禅宗大兴，临济宗分化为黄龙派和杨岐派，曹洞宗提倡默照禅，禅宗'五家七宗'格局完全确立，有'临济遍天下'之称。",
    category: "宗派创立",
    location: "全国",
  },
  {
    slug: "wumen-guan",
    year: 1228,
    yearDisplay: "公元 1228 年",
    title: "《无门关》与《碧岩录》编成",
    description: "无门慧开编《无门关》四十八则公案，圜悟克勤著《碧岩录》评唱百则古则，禅宗公案文学达到顶峰，对后世禅宗乃至东亚文化影响深远。",
    category: "经典译出",
    location: "南宋",
  },

  // ===== 元明清 =====
  {
    slug: "tsongkhapa",
    year: 1409,
    yearDisplay: "公元 1409 年",
    title: "宗喀巴创立格鲁派",
    description: "宗喀巴大师在拉萨举行大昭寺祈愿大法会，建立甘丹寺，著《菩提道次第广论》，创立藏传佛教格鲁派（黄教），达赖与班禅两大活佛转世系统自此开端。",
    category: "宗派创立",
    location: "拉萨",
  },
  {
    slug: "ming-qing-tripitaka",
    year: 1738,
    yearDisplay: "公元 1738 年",
    title: "《乾隆大藏经》刊印",
    description: "清雍正帝敕修、乾隆初年完成的《龙藏》共7168卷，是中国封建社会最后一部官修大藏经，板存柏林寺，至今完好。",
    category: "经典译出",
    location: "北京",
  },

  // ===== 近现代 =====
  {
    slug: "pali-text-society",
    year: 1881,
    yearDisplay: "公元 1881 年",
    title: "巴利圣典协会成立",
    description: "英国学者戴维斯（T.W. Rhys Davids）在伦敦创立巴利圣典协会（PTS），系统整理出版巴利三藏罗马字转写本，开启现代佛教学术研究。",
    category: "历史事件",
    location: "伦敦",
  },
  {
    slug: "dunhuang-discovery",
    year: 1900,
    yearDisplay: "公元 1900 年",
    title: "敦煌莫高窟藏经洞发现",
    description: "道士王圆箓在敦煌莫高窟发现封闭近千年的藏经洞，出土公元5-11世纪佛教写本约5万件，为研究佛教史和中西交流提供了空前绝后的原始资料。",
    category: "历史事件",
    location: "敦煌",
  },
  {
    slug: "taixu-reform",
    year: 1922,
    yearDisplay: "公元 1922 年",
    title: "太虚大师倡导人生佛教",
    description: "太虚大师创办武昌佛学院，提出'人生佛教'理念和'教理、教制、教产'三大革命纲领，推动中国佛教从出世转向入世的现代化改革。",
    category: "人物",
    location: "武昌",
  },
  {
    slug: "taisho-tripitaka",
    year: 1934,
    yearDisplay: "公元 1924–1934 年",
    title: "《大正新修大藏经》刊行",
    description: "高楠顺次郎与渡边海旭主编的《大正新修大藏经》100卷在日本出版，是现代佛教学术研究最通用的汉文大藏经版本，也是CBETA的底本。",
    category: "经典译出",
    location: "东京",
  },
  {
    slug: "cbeta",
    year: 1998,
    yearDisplay: "公元 1998 年",
    title: "CBETA 中华电子佛典协会成立",
    description: "CBETA 开始将大正新修大藏经全文数字化，成为中文互联网上最权威的免费佛典数据库，彻底改变了佛教学术研究的方法。",
    category: "历史事件",
    location: "台北",
  },
  {
    slug: "cibei-launch",
    year: 2026,
    yearDisplay: "2026 年",
    title: "慈悲空间 Cibei Space 上线",
    description: "慈悲空间正式上线，提供经典库、佛学词典、百科、佛经故事、历史时间线及AI辅助研读功能，致力于成为中文互联网最完整的佛学知识库与学习平台。",
    category: "历史事件",
    location: "线上",
  },

  // ===== 印度早期补充 =====
  {
    slug: "sariputra-maudgalyayana",
    year: -528,
    yearDisplay: "约 公元前 528 年",
    title: "舍利弗与目犍连皈依",
    description: "佛陀成道后不久，王舍城著名游方学者舍利弗与目犍连率二百五十弟子皈依佛陀，二人后来成为佛陀十大弟子之首，分别被誉为'智慧第一'与'神通第一'。",
    category: "人物",
    location: "王舍城（今印度比哈尔邦）",
  },
  {
    slug: "major-sects-emerge",
    year: -280,
    yearDisplay: "约 公元前 3 世纪",
    title: "部派佛教十八部形成",
    description: "第二次结集后上座部与大众部根本分裂，此后两百年间进一步分化为十八部派（南传称十八部，北传称二十部），各部在戒律与教义上各有发展，进入部派佛教时代。",
    category: "历史事件",
    location: "古印度各地",
  },
  {
    slug: "pali-canon-written",
    year: -29,
    yearDisplay: "约 公元前 29 年",
    title: "巴利三藏写成文字",
    description: "斯里兰卡大寺五百比丘在阿卢寺举行第四次结集，将口诵传承的巴利三藏首次以文字形式记录在贝叶上，是为现存最完整的早期佛教经典体系。",
    category: "经典译出",
    location: "斯里兰卡阿卢寺",
  },
  {
    slug: "nalanda-founded",
    year: 427,
    yearDisplay: "约 公元 5 世纪",
    title: "那烂陀寺建立",
    description: "笈多王朝鸠摩罗笈多一世在那烂陀建立佛教大学，此后数百年间成为印度乃至世界最大的佛教学术中心，鼎盛时期有万余僧侣学者在此研习，玄奘、义净等皆曾在此求学。",
    category: "圣地",
    location: "那烂陀（今印度比哈尔邦）",
  },

  // ===== 佛教南传东南亚 =====
  {
    slug: "buddhism-enters-vietnam",
    year: 200,
    yearDisplay: "约 公元 2 世纪",
    title: "佛教传入越南",
    description: "佛教经由印度与中国两条路线传入交趾（今越南北部），牟子在此著《理惑论》，以中国本土思想阐释佛教义理，是中外佛教思想对话的最早文献之一。",
    category: "历史事件",
    location: "交趾（今越南）",
  },
  {
    slug: "bagan-buddhism",
    year: 1050,
    yearDisplay: "约 公元 11 世纪中期",
    title: "缅甸蒲甘王朝确立上座部佛教",
    description: "蒲甘王朝阿奴律陀王皈依上座部佛教，迎请斯里兰卡高僧弘法，兴建大量佛塔寺院，蒲甘成为东南亚上座部佛教中心，'万塔之城'之誉流传至今。",
    category: "历史事件",
    location: "蒲甘（今缅甸）",
  },
  {
    slug: "angkor-buddhist",
    year: 1181,
    yearDisplay: "约 公元 1181 年",
    title: "阇耶跋摩七世改奉大乘佛教",
    description: "阇耶跋摩七世登基后将吴哥王朝国教从印度教转为大乘佛教，兴建巴扬寺等宏伟佛教建筑，吴哥王城成为当时东南亚最壮观的佛教中心。",
    category: "历史事件",
    location: "吴哥（今柬埔寨暹粒）",
  },
  {
    slug: "sukhothai-theravada",
    year: 1283,
    yearDisplay: "约 公元 1283 年",
    title: "素可泰王朝确立上座部佛教为泰国国教",
    description: "兰甘亨大王迎请斯里兰卡系上座部高僧至素可泰传法，确立上座部佛教为泰王国国教，至今泰国仍是南传佛教最重要的传播中心之一。",
    category: "历史事件",
    location: "素可泰（今泰国）",
  },

  // ===== 藏传佛教 =====
  {
    slug: "songtsen-gampo",
    year: 641,
    yearDisplay: "公元 641 年",
    title: "松赞干布迎娶文成公主与尺尊公主",
    description: "吐蕃赞普松赞干布迎娶尼泊尔尺尊公主与唐朝文成公主，两位公主各自带入佛像与佛经，拉萨兴建大昭寺与小昭寺供奉佛像，佛教正式传入西藏。",
    category: "历史事件",
    location: "拉萨",
  },
  {
    slug: "padmasambhava-tibet",
    year: 779,
    yearDisplay: "约 公元 779 年",
    title: "赤松德赞迎请莲花生大师入藏",
    description: "吐蕃赞普赤松德赞迎请印度密法大师莲花生（Padmasambhava）入藏，莲花生一路降伏苯教神祇收归为佛教护法，奠定了宁玛派（旧译派）的教法基础。",
    category: "人物",
    location: "西藏",
  },
  {
    slug: "samye-monastery",
    year: 779,
    yearDisplay: "约 公元 779 年",
    title: "桑耶寺建立——西藏第一座佛教寺院",
    description: "赤松德赞敕建桑耶寺，由莲花生大师选址、寂护大师设计，按佛教宇宙观布局，首批'七觉士'在此剃度出家，标志着佛教在西藏的正式确立。",
    category: "圣地",
    location: "桑耶（今西藏山南）",
  },
  {
    slug: "atisha-tibet",
    year: 1042,
    yearDisplay: "公元 1042 年",
    title: "阿底峡尊者入藏弘法",
    description: "印度超岩寺首座阿底峡尊者应古格王朝拉喇嘛益西沃之请入藏，著《菩提道灯论》系统阐述三士道次第，整顿西藏密乘乱象，开创噶当派，其后传影响宗喀巴格鲁派之建立。",
    category: "人物",
    location: "古格→藏地",
  },
  {
    slug: "milarepa",
    year: 1050,
    yearDisplay: "约 公元 1040–1123 年",
    title: "米拉日巴——西藏最著名的瑜伽行者",
    description: "米拉日巴师从马尔巴学习那若六法与大手印，以苦修著称，后以道歌（即'十万歌集'）教授弟子，是噶举派最具代表性的成就者，其生平故事影响了无数修行者。",
    category: "人物",
    location: "西藏",
  },
  {
    slug: "phagpa-yuan",
    year: 1253,
    yearDisplay: "公元 1253 年",
    title: "八思巴会见忽必烈——萨迦派统领西藏",
    description: "萨迦派第五祖八思巴与忽必烈会面，后受封为帝师，统领天下释教兼领西藏，开创了西藏政教合一制度，八思巴创制蒙古新字对元朝文化产生深远影响。",
    category: "历史事件",
    location: "六盘山→大都",
  },

  // ===== 日本佛教 =====
  {
    slug: "saicho-tendai",
    year: 805,
    yearDisplay: "公元 805 年",
    title: "最澄传入天台宗——日本天台宗创立",
    description: "最澄（传教大师）入唐在天台山学习天台宗教法，回国后在比叡山建立延历寺，开创日本天台宗，将天台、密、禅、戒四宗兼学，成为后世日本佛教各宗之母山。",
    category: "宗派创立",
    location: "比叡山（日本京都）",
  },
  {
    slug: "kukai-shingon",
    year: 806,
    yearDisplay: "公元 806 年",
    title: "空海传入真言宗——日本密宗创立",
    description: "空海（弘法大师）入唐师从惠果学习密法，回国后在高野山开创真言宗，著《十住心论》系统判释佛教各宗，将唐密完整移植日本并传承至今，高野山成为日本佛教圣地。",
    category: "宗派创立",
    location: "高野山（日本和歌山）",
  },
  {
    slug: "honen-jodo",
    year: 1175,
    yearDisplay: "公元 1175 年",
    title: "法然开创净土宗——专修念佛",
    description: "法然（源空）在比叡山修学后，依善导'他力本愿'思想开创净土宗，提倡'专修念佛'——一心称念南无阿弥陀佛即可往生净土，净土信仰走向民间大众。",
    category: "宗派创立",
    location: "日本京都",
  },
  {
    slug: "dogen-soto",
    year: 1227,
    yearDisplay: "公元 1227 年",
    title: "道元传入曹洞宗——只管打坐",
    description: "道元入宋师从天童如净学习曹洞禅法，回国后著《正法眼藏》95卷，提倡'只管打坐'的默照禅法，开创日本曹洞宗，永平寺为其根本道场。",
    category: "宗派创立",
    location: "日本福井永平寺",
  },

  // ===== 韩国佛教 =====
  {
    slug: "buddhism-enters-korea",
    year: 372,
    yearDisplay: "公元 372 年",
    title: "佛教传入朝鲜半岛",
    description: "前秦苻坚派僧顺道送佛像与经文至高句丽，佛教正式开始在朝鲜半岛传播。百济（384）与新罗（5世纪）相继接受佛教，成为朝鲜三国时代的主要信仰。",
    category: "历史事件",
    location: "高句丽（今朝鲜半岛北部）",
  },
  {
    slug: "wonhyo-uisang",
    year: 660,
    yearDisplay: "约 公元 660 年",
    title: "元晓大师与义湘——海东佛教思想奠基",
    description: "元晓著《大乘起信论疏》等百余部著作，以'一心'思想会通诸宗，是韩国佛教史上最具原创力的思想家；义湘入唐师从智俨学习华严，回国开创海东华严宗，建浮石寺弘法。",
    category: "人物",
    location: "新罗（今韩国）",
  },

  // ===== 唐代补充 =====
  {
    slug: "yijing-pilgrimage",
    year: 671,
    yearDisplay: "公元 671–695 年",
    title: "义净西行求法",
    description: "义净法师从广州乘船经海路至印度，在那烂陀寺学习十年，归途中在室利佛逝著述《南海寄归内法传》与《大唐西域求法高僧传》，记载了唐朝五十余位西行僧人行迹与南海佛教状况。",
    category: "人物",
    location: "广州→印度→室利佛逝",
  },
  {
    slug: "wu-zetian-huayan",
    year: 695,
    yearDisplay: "约 公元 695 年",
    title: "武则天与华严宗",
    description: "武则天推崇《华严经》，迎请法藏（贤首国师）入宫讲经，并资助实叉难陀重新翻译《华严经》八十卷（八十华严），华严宗在女皇支持下达到弘传高峰，'华严'教义渗透到中国佛教各宗。",
    category: "历史事件",
    location: "洛阳",
  },
  {
    slug: "shenhui-debate",
    year: 734,
    yearDisplay: "公元 734 年",
    title: "神会滑台大会——禅宗南北之争",
    description: "荷泽神会在滑台大云寺无遮大会上，公开指责北宗神秀门下'师承是傍、法门是渐'，确立慧能为禅宗六祖的正统地位，南宗顿教由此取得主导，禅宗历史叙事由此改写。",
    category: "历史事件",
    location: "滑台（今河南滑县）",
  },

  // ===== 宋元补充 =====
  {
    slug: "tripitaka-koreana",
    year: 1236,
    yearDisplay: "公元 1236–1251 年",
    title: "高丽大藏经雕刻",
    description: "高丽高宗为抵御蒙古入侵，举国祈愿雕刻大藏经，雕版八万余块藏于海印寺，至今完整保存。其底本精校多种大藏经版本，是学界公认质量最优的汉文大藏经之一。",
    category: "经典译出",
    location: "高丽（今韩国海印寺）",
  },
  {
    slug: "zhaocheng-jin-tripitaka",
    year: 1149,
    yearDisplay: "公元 1149–1173 年",
    title: "赵城金藏雕刻",
    description: "金代民间崔法珍断臂募缘发起雕刻大藏经，依《开宝藏》为底本，历时二十余年完成，现存于国家图书馆。是研究《开宝藏》与中国雕版印刷史的关键实物，与《永乐大典》等并列国图四大镇馆之宝。",
    category: "经典译出",
    location: "金国（今山西赵城）",
  },

  // ===== 明清补充 =====
  {
    slug: "zibo-jiaxing-tripitaka",
    year: 1589,
    yearDisplay: "公元 1589 年",
    title: "紫柏真可与《嘉兴藏》",
    description: "紫柏真可大师感于明代大藏经板藏官府不便流通，发起民间募资刊刻《嘉兴藏》（方册藏），改梵夹本为方册本便于阅读传播，开创民间刻印大藏经之先河。",
    category: "经典译出",
    location: "嘉兴",
  },
  {
    slug: "yang-wenhui-jinling",
    year: 1866,
    yearDisplay: "公元 1866 年",
    title: "杨文会创立金陵刻经处",
    description: "杨文会（杨仁山）居士在南京创立金陵刻经处，系统刻印流通佛教经典，开办祇洹精舍兴办僧教育，培养太虚、欧阳竟无等现代佛教领袖，被誉为'中国近代佛教复兴之父'。",
    category: "历史事件",
    location: "南京",
  },

  // ===== 近现代补充 =====
  {
    slug: "sri-lanka-revival",
    year: 1891,
    yearDisplay: "公元 1891 年",
    title: "达摩波罗与斯里兰卡佛教复兴",
    description: "阿那伽里迦·达摩波罗（Anagarika Dharmapala）创立摩诃菩提会，发起恢复菩提伽耶佛教圣地的国际运动，推动斯里兰卡佛教教育与社会改革，现代上座部民族主义佛教复兴由此展开。",
    category: "人物",
    location: "斯里兰卡科伦坡",
  },
  {
    slug: "world-fellowship-buddhists",
    year: 1950,
    yearDisplay: "公元 1950 年",
    title: "世界佛教徒联谊会成立",
    description: "首届世界佛教徒联谊会（世佛联，WFB）在斯里兰卡科伦坡召开，29个国家代表参加，是第一个全球性佛教国际组织，总部设于曼谷，每两年举行一次大会。",
    category: "历史事件",
    location: "斯里兰卡科伦坡",
  },
  {
    slug: "chinese-buddhist-academy",
    year: 1956,
    yearDisplay: "公元 1956 年",
    title: "中国佛学院成立",
    description: "中国佛学院在北京法源寺成立，由中国佛教协会创办，喜饶嘉措大师任首任院长，法尊法师等执教，是新中国第一所全国性高等佛学院，培养了大量僧才。",
    category: "历史事件",
    location: "北京法源寺",
  },
  {
    slug: "dalai-lama-exile",
    year: 1959,
    yearDisplay: "公元 1959 年",
    title: "第十四世达赖喇嘛流亡印度",
    description: "1959年西藏发生重大政治变动，第十四世达赖喇嘛出走印度，在达兰萨拉建立流亡政府，西藏佛教自此在海外广泛传播，藏传佛教的传承体系面临根本性变革。",
    category: "历史事件",
    location: "拉萨→印度达兰萨拉",
  },
  {
    slug: "thich-nhat-hanh",
    year: 1964,
    yearDisplay: "公元 1964 年",
    title: "一行禅师创立'入世佛教'",
    description: "越南僧侣一行禅师（Thich Nhat Hanh）在越战期间创立相即共修团，倡导'入世佛教'（Engaged Buddhism）——将正念修习与社会行动结合，后来在法国建立梅村禅修中心，影响遍及全球。",
    category: "人物",
    location: "越南→法国梅村",
  },

  // ===== 当代佛教 =====
  {
    slug: "tzu-chi-foundation",
    year: 1966,
    yearDisplay: "公元 1966 年",
    title: "证严法师创立慈济功德会",
    description: "证严法师在台湾花莲以'慈悲为怀、济世为志'创立慈济功德会，从三十位家庭主妇日存五毛钱起步，发展为全球最大佛教慈善组织，在医疗、教育、赈灾等领域持续深耕。",
    category: "宗派创立",
    location: "花莲（台湾）",
  },
  {
    slug: "fo-guang-shan",
    year: 1967,
    yearDisplay: "公元 1967 年",
    title: "星云大师开创佛光山",
    description: "星云大师在高雄大树乡开创佛光山，以'人间佛教'为宗旨，建立全球性的僧团、教育与文化体系，在全球五大洲建立三百余道场，是当代汉传佛教最具国际影响力的僧团之一。",
    category: "宗派创立",
    location: "高雄（台湾）",
  },
  {
    slug: "dharma-drum-mountain",
    year: 1989,
    yearDisplay: "公元 1989 年",
    title: "圣严法师创办法鼓山",
    description: "圣严法师在台北金山创办法鼓山，以'提升人的品质，建设人间净土'为理念，倡导心灵环保、礼仪环保等，法鼓山中华佛学研究所与僧伽大学成为现代汉传佛教教育的重要基地。",
    category: "宗派创立",
    location: "台北金山（台湾）",
  },
];
